// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1MzuEgjpNpCMmFdBaV_ep5bCtWDPlKqg',
    appId: '1:935660613089:web:b3209a58442fa1999336a0',
    messagingSenderId: '935660613089',
    projectId: 'hemantenterprises-547bf',
    authDomain: 'hemantenterprises-547bf.firebaseapp.com',
    storageBucket: 'hemantenterprises-547bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD69NSpQwXfK6IXD8eSFoRwaOmmO6tMTu4',
    appId: '1:935660613089:android:72c69c70421a744c9336a0',
    messagingSenderId: '935660613089',
    projectId: 'hemantenterprises-547bf',
    storageBucket: 'hemantenterprises-547bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWGRYwKW2sBiHhSqbCnYfhxjahzXH3rKw',
    appId: '1:935660613089:ios:b54ff76138d345f29336a0',
    messagingSenderId: '935660613089',
    projectId: 'hemantenterprises-547bf',
    storageBucket: 'hemantenterprises-547bf.firebasestorage.app',
    iosBundleId: 'com.hemantenterprises.hemantenterprises',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWGRYwKW2sBiHhSqbCnYfhxjahzXH3rKw',
    appId: '1:935660613089:ios:b54ff76138d345f29336a0',
    messagingSenderId: '935660613089',
    projectId: 'hemantenterprises-547bf',
    storageBucket: 'hemantenterprises-547bf.firebasestorage.app',
    iosBundleId: 'com.hemantenterprises.hemantenterprises',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1MzuEgjpNpCMmFdBaV_ep5bCtWDPlKqg',
    appId: '1:935660613089:web:b85335e04cd25d939336a0',
    messagingSenderId: '935660613089',
    projectId: 'hemantenterprises-547bf',
    authDomain: 'hemantenterprises-547bf.firebaseapp.com',
    storageBucket: 'hemantenterprises-547bf.firebasestorage.app',
  );
}
