// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNFvrKfKBv4ylZclHBkt47jFVt2s_ddIA',
    appId: '1:420845502095:web:ef35107ffc0e1331b2bafa',
    messagingSenderId: '420845502095',
    projectId: 'hemantenterprises-70732',
    authDomain: 'hemantenterprises-70732.firebaseapp.com',
    storageBucket: 'hemantenterprises-70732.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCAOnOatouCh-K-adFaF-SF40oQTAwFW0',
    appId: '1:420845502095:android:bc95a034ca3192d3b2bafa',
    messagingSenderId: '420845502095',
    projectId: 'hemantenterprises-70732',
    storageBucket: 'hemantenterprises-70732.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5DB3Q9lIHxYS2pVlvpNYzsQpuUcHVO6I',
    appId: '1:420845502095:ios:21d076c94d32369fb2bafa',
    messagingSenderId: '420845502095',
    projectId: 'hemantenterprises-70732',
    storageBucket: 'hemantenterprises-70732.firebasestorage.app',
    iosBundleId: 'com.hemantenterprises.hemantenterprises',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5DB3Q9lIHxYS2pVlvpNYzsQpuUcHVO6I',
    appId: '1:420845502095:ios:21d076c94d32369fb2bafa',
    messagingSenderId: '420845502095',
    projectId: 'hemantenterprises-70732',
    storageBucket: 'hemantenterprises-70732.firebasestorage.app',
    iosBundleId: 'com.hemantenterprises.hemantenterprises',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNFvrKfKBv4ylZclHBkt47jFVt2s_ddIA',
    appId: '1:420845502095:web:19578cfe111bd02cb2bafa',
    messagingSenderId: '420845502095',
    projectId: 'hemantenterprises-70732',
    authDomain: 'hemantenterprises-70732.firebaseapp.com',
    storageBucket: 'hemantenterprises-70732.firebasestorage.app',
  );
}
